apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: jenkins
  namespace: cicd-platform
spec:
  destination:
    name: ''
    namespace: cicd-platform
    server: 'https://kubernetes.default.svc'
  source:
    path: jenkins/master
    repoURL: 'JENKINS_GIT_URL'
    targetRevision: HEAD
  project: default
  syncPolicy:
    automated: {}


