apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: jenkins
spec:
  destination:
    name: ''
    namespace: cicd-platform
    server: 'https://kubernetes.default.svc'
  source:
    path: jenkins/master
    repoURL: 'https://github.com/petrenyim/cicd-platform.git'
    targetRevision: HEAD
  project: default

